# CONSULTAS QUE SE EJECUTAN DENTRO DE OTRAS Y CONSISTEN EN UTILIZAR
LOS RESULTADOS DE LA SUBCONSULTA PARA OPERAR EN LA CONSULTA PRINCIPAL
USANDO LAS CLAVES FORANEAS #

SELECT * FROM usuarios WHERE id IN (SELECT usuario_id FROM entradas);

# OBTENER LOS USUARIOS QUE TENGAN ELDEN RING EN EL TITULO DE SUS ENTRADAS #
SELECT nombre, apellidos FROM usuarios WHERE id IN (SELECT usuario_id FROM entradas WHERE titulo LIKE "%elden ring%");

# OBTENER TODAS LAS ENTRADAS DE LA CATEGORIA RPG #
SELECT titulo FROM entradas WHERE categoria_id IN (SELECT id FROM categorias WHERE nombre LIKE "RPG");

# MOSTRAR LAS CATEGORIAS CON MAS DE 3 O MAS ENTRADAS #
SELECT nombre FROM categorias WHERE id IN (SELECT categoria_id FROM entradas GROUP BY categoria_id HAVING COUNT(categoria_id) >= 3);

# MOSTRAR LOS USUARIOS QUE CREARON UNA ENTRADA UN MARTES #
SELECT nombre, apellidos FROM usuarios WHERE id IN (SELECT usuario_id FROM entradas WHERE DAYOFWEEK(fecha) = 3);

# MOSTRAR EL NOMBRE DEL USUARIO QUE TENGA MAS ENTRADAS #
SELECT nombre, apellidos FROM usuarios WHERE id IN (SELECT usuario_id FROM entradas GROUP BY usuario_id ORDER BY COUNT(id) DESC LIMIT 1);

# MOSTRAR LAS CATEGORIAS SIN ENTRADAS #
SELECT * FROM categorias WHERE id NOT IN (SELECT categoria_id FROM entradas);